### ISSUE TITLE
train_contrastive_loss

### ISSUE THREAD

**Issue by AaronWong** [woshihaozhu/ContraTalkingFace#1]
你好，你的研究工作很不错
用了 train_contrastive_loss 来训练 效果好么？

还在学校读书么，我们也在做talking face的相关工作，可以交流下么？

**Comment by junwenxiong** [comment]
用contrastive_loss效果一般吧。

**Comment by AaronWong** [comment]
syncnet和wav2lip可以稳定训练么

https://github.com/Hangz-nju-cuhk/Talking-Face_PC-AVS

![图片](https://user-images.githubusercontent.com/10103794/143332012-228a51f1-44ed-4e92-9a20-491b40a9e642.png)
周韩博士用了 InfoNCE，可以参考下

**Comment by junwenxiong** [comment]
嗯，两者是可以稳定训练的。Pose这篇文章我们也跑了demo，但是效果很差。
